name = "quicksort"
testDriver = "test"
defaultTargets = [
  "Quicksort", 
  "quicksort", 
  # "Bench",
]

[[lean_lib]]
name = "Quicksort"

[[lean_exe]]
name = "quicksort"
root = "Example"

# [[lean_exe]]
# name = "timer"
# root = "Timer_Issue"
# srcDir = "Bench"

# [[lean_exe]]
# name = "test"
# srcDir = "Bench"
# root = "Main"

# [[lean_lib]]
# name = "Bench"
# defaultFacets = ["shared"]    # defaultFacets := #[LeanLib.sharedFacet]

# [[lean_exe]]
# name = "hoaretest"
# srcDir = "Bench"
# root = "Hoare"
# moreLeancArgs = ["-O3"]



[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.30.0"






# import Lake
# open System Lake DSL



# @[default_target]
# lean_lib Bench where
