name = "SortBench"
version = "0.1.0"
defaultTargets = ["bench"]
testDriver = "test"


[[lean_lib]]
name = "DataGen"

[[lean_exe]]
name = "datagen"
root = "Main"
srcDir = "DataGen"
buildType = "release"

[[lean_exe]]
name = "test"
root = "Test"
buildType = "relWithDebInfo"



[[lean_lib]]
name = "Bench"
# roots = ["Basic"]
# srcDir = "src/Lean"



[[lean_exe]]
name = "bench"
root = "Main"
buildType = "release"
# cflags = ["-O3", "-march=native"]
# lflags = ["-static"]
# release = true 
srcDir = "src/Lean"
# needs = ["Bench"]




[[require]]
name = "quicksort"
path = ".."


[[require]]
name = "Cli"
path = ".."

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "v4.22.0+patch1"
